
/**
 *
 * @author RaulL
 */
public class RAULFRAME extends javax.swing.JFrame {
   
    /** Creates new form RAULFRAME */
    public RAULFRAME() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

   
    private void initComponents() {//GEN-BEGIN:initComponents

        rAULPANEL21 = new RAULPANEL2();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout rAULPANEL21Layout = new javax.swing.GroupLayout(rAULPANEL21);
        rAULPANEL21.setLayout(rAULPANEL21Layout);
        rAULPANEL21Layout.setHorizontalGroup(
            rAULPANEL21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        rAULPANEL21Layout.setVerticalGroup(
            rAULPANEL21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        jButton3.setText("C0L");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("C0R");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });

        jButton4.setText("C1LEFT");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("C1RIGHT");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Left");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });

        jButton7.setText("Right");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });

        jButton8.setText("POS1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("POS2");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setText("SAVE POS1");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("SAVE POS2");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rAULPANEL21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(rAULPANEL21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)))
        );

        pack();
    }//GEN-END:initComponents
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //START
       // rAULPANEL21.ReverseBoth=false;
      // rAULPANEL21.afisare=true;
       // rAULPANEL21.AfisareInitiala=false;
        //rAULPANEL21.StartToStop=true;
       // rAULPANEL21.ReverseToStop=false;
      // rAULPANEL21.repaint();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //REVERSEBOTH
       
        //rAULPANEL21.ReverseBoth=true;
      // rAULPANEL21.afisare=true;
       // rAULPANEL21.AfisareInitiala=false;
       // rAULPANEL21.StartToStop=false;
       // rAULPANEL21.ReverseToStop=true;
       // repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        //C1LPRESSED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=true;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;            
                repaint();
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        // TODO add your handling code here:
        //C1LRELEASED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=true;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
        
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
//BUTON C0L MOUSE PRESSED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=true;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
        //C0L MOUSE RELEASED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=true;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2KeyReleased

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        //C0R MOUSE PRESSED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=true;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        //C0R MOUSE RELEASED
        rAULPANEL21.C0RReleased=true;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        //C1R PRESSED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=true;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
        
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        // TODO add your handling code here:
        //C1R RELEASED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=true;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;         
                repaint();
                
    }//GEN-LAST:event_jButton5MouseReleased

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
        //LEFTPRESS
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=true;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=false;
        rAULPANEL21.RIGHTRELEASE=false;
        repaint();
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        // TODO add your handling code here:
       // LEFTRELEASE
       rAULPANEL21.C0RReleased=false;
              rAULPANEL21.afisare=false;
               rAULPANEL21.AfisareInitiala=false;
               rAULPANEL21.C0LRELEASED=false;
               rAULPANEL21.C1LReleased=false;
       rAULPANEL21.C1Left=false;
       rAULPANEL21.C1Right=false;
       rAULPANEL21.C0Left=false;
       rAULPANEL21.C0Right=false;
       rAULPANEL21.C1RRELEASED=false;
       rAULPANEL21.LEFTPRESS=false;
       rAULPANEL21.LEFTRELEASE=true;
       rAULPANEL21.RIGHTPRESS=false;
       rAULPANEL21.RIGHTRELEASE=false;
       repaint();
    }//GEN-LAST:event_jButton6MouseReleased

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        //RIGHTPRESSED
        rAULPANEL21.C0RReleased=false;
               rAULPANEL21.afisare=false;
                rAULPANEL21.AfisareInitiala=false;
                rAULPANEL21.C0LRELEASED=false;
                rAULPANEL21.C1LReleased=false;
        rAULPANEL21.C1Left=false;
        rAULPANEL21.C1Right=false;
        rAULPANEL21.C0Left=false;
        rAULPANEL21.C0Right=false;
        rAULPANEL21.C1RRELEASED=false;
        rAULPANEL21.LEFTPRESS=false;
        rAULPANEL21.LEFTRELEASE=false;
        rAULPANEL21.RIGHTPRESS=true;
        rAULPANEL21.RIGHTRELEASE=false;
        repaint();
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        // TODO add your handling code here:
       // RIGHTRLEASE
       rAULPANEL21.C0RReleased=false;
              rAULPANEL21.afisare=false;
               rAULPANEL21.AfisareInitiala=false;
               rAULPANEL21.C0LRELEASED=false;
               rAULPANEL21.C1LReleased=false;
       rAULPANEL21.C1Left=false;
       rAULPANEL21.C1Right=false;
       rAULPANEL21.C0Left=false;
       rAULPANEL21.C0Right=false;
       rAULPANEL21.C1RRELEASED=false;
       rAULPANEL21.LEFTPRESS=false;
       rAULPANEL21.LEFTRELEASE=false;
       rAULPANEL21.RIGHTPRESS=false;
       rAULPANEL21.RIGHTRELEASE=true;
       repaint();
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // SAVE POS1
        System.out.println("POS1 SAVED");
         rAULPANEL21.i1=rAULPANEL21.i;
        rAULPANEL21.b1=rAULPANEL21.b;
        rAULPANEL21.c1=rAULPANEL21.c;
        rAULPANEL21.d1=rAULPANEL21.d;
        rAULPANEL21.e1=rAULPANEL21.e;
        rAULPANEL21.a1=rAULPANEL21.a;
        rAULPANEL21.h1=rAULPANEL21.h;
        rAULPANEL21.k1=rAULPANEL21.k;
        
        
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        //SAVE BUTTON CLICK
        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // POS1
        rAULPANEL21.i=rAULPANEL21.i1;
        rAULPANEL21.b=rAULPANEL21.b1;
        rAULPANEL21.c=rAULPANEL21.c1;
        rAULPANEL21.d=rAULPANEL21.d1;
        rAULPANEL21.e=rAULPANEL21.e1;
        rAULPANEL21.a=rAULPANEL21.a1;
        rAULPANEL21.h=rAULPANEL21.h1;
        rAULPANEL21.k=rAULPANEL21.k1;
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // SAVE POS2
        System.out.println("POS2 SAVED");
        rAULPANEL21.i2=rAULPANEL21.i;
        rAULPANEL21.b2=rAULPANEL21.b;
        rAULPANEL21.c2=rAULPANEL21.c;
        rAULPANEL21.d2=rAULPANEL21.d;
        rAULPANEL21.e2=rAULPANEL21.e;
        rAULPANEL21.a2=rAULPANEL21.a;
        rAULPANEL21.h2=rAULPANEL21.h;
        rAULPANEL21.k2=rAULPANEL21.k;
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // POS2
        rAULPANEL21.i=rAULPANEL21.i2;
        rAULPANEL21.b=rAULPANEL21.b2;
        rAULPANEL21.c=rAULPANEL21.c2;
        rAULPANEL21.d=rAULPANEL21.d2;
        rAULPANEL21.e=rAULPANEL21.e2;
        rAULPANEL21.a=rAULPANEL21.a2;
        rAULPANEL21.h=rAULPANEL21.h2;
        rAULPANEL21.k=rAULPANEL21.k2;
        
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(RAULFRAME.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(RAULFRAME.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(RAULFRAME.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(RAULFRAME.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new RAULFRAME().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private RAULPANEL2 rAULPANEL21;
    // End of variables declaration//GEN-END:variables

}
